### ISSUE TITLE
boolean operators produce incorrect values

### ISSUE THREAD

**Issue by MouthOfMadness** [MathewSachin/Arpian#26]
When I use the Boolean operators, I get the following results.

7 & 4 = 1, should be 4
0111 & 0100 = 0100

7 & 8 = 1, should be 0
0111 & 1000 = 0000

7 | 8 = 1, should be 15
0111 | 1000 = 1111

**Comment by MathewSachin** [comment]
I'm sorry but `&` is implemented as a Logical operator and every number except 0 is treated as `true`

**Comment by MouthOfMadness** [comment]
It’s not grouped that way, I’ve tried changing the source to be.

new BinaryBooleanOperator("&", 1, (x, y) => x & y),

But I still get the same result.


SharedOperators.Add
            (
                Plus,
                Minus,
                Multiply,
                new BinaryOperator<double>("^", 10, Math.Pow) { IsRightAssociated = true },
                new BinaryOperator<double>("/", 7, (x, y) => x / y),
                new BinaryOperator<double>("%", 10, (x, y) => x % y),
                new ComparisonOperator("==", 3, (x, y) => x == y),
                new ComparisonOperator("!=", 3, (x, y) => x != y),
                new ComparisonOperator(">", 3, (x, y) => x > y),
                new ComparisonOperator("<", 3, (x, y) => x < y),
                new ComparisonOperator(">=", 3, (x, y) => x >= y),
                new ComparisonOperator("<=", 3, (x, y) => x <= y),
                new BinaryBooleanOperator("&", 1, (x, y) => x && y),
                new BinaryBooleanOperator("|", 1, (x, y) => x || y),
                new UnaryOperator<double>("~", 8, x => x == 0 ? 1 : 0),
                new BinaryOperator<double>(">>", 1, (x, y) => (int)x >> (int)y),
                new BinaryOperator<double>("<<", 1, (x, y) => (int)x << (int)y)
            );

**Comment by MouthOfMadness** [comment]
That’s the ticket.
